export const product = [
  {
    id: 1,
    img: "Img/productosCremas/crema 1.jpg",
    title: "Crema 1",
    price: 43900,
    stock: 50,
    description: "Crema hidratante ideal para todo tipo de piel.",
  },
  {
    id: 2,
    img: "Img/productosCremas/crema nivea.webp",
    title: "Crema Nivea",
    price: 49000,
    stock: 40,
    description: "Nutre y suaviza la piel con su fórmula clásica.",
  },
  {
    id: 3,
    img: "Img/productosCremas/dove 2.png",
    title: "Dove 2",
    price: 46000,
    stock: 30,
    description: "Crema rica en nutrientes para una piel radiante.",
  },
  {
    id: 4,
    img: "Img/productosCremas/neutrogena.jpg",
    title: "Neutrogena",
    price: 67000,
    stock: 25,
    description: "Hidratación profunda para una piel saludable.",
  },
  {
    id: 5,
    img: "Img/productosCremas/tododia.jpg",
    title: "Tododia",
    price: 39000,
    stock: 60,
    description: "Crema corporal con fragancia fresca y ligera.",
  },
  {
    id: 6,
    img: "Img/productosCremas/vitu.webp",
    title: "Vitu",
    price: 72000,
    stock: 20,
    description: "Fórmula avanzada para el cuidado de la piel.",
  },
  {
    id: 7,
    img: "Img/productosExfoliantes/exfoliante cafe.jpg",
    title: "Exfoliante Café",
    price: 33000,
    stock: 50,
    description: "Exfoliante natural que revitaliza la piel.",
  },
  {
    id: 8,
    img: "Img/productosExfoliantes/exfoliante olivia.webp",
    title: "Exfoliante Olivia",
    price: 28000,
    stock: 45,
    description: "Suave exfoliación con ingredientes orgánicos.",
  },
  {
    id: 9,
    img: "Img/productosExfoliantes/exfoliante.jpg",
    title: "Exfoliante",
    price: 32000,
    stock: 35,
    description: "Elimina las células muertas y renueva la piel.",
  },
  {
    id: 10,
    img: "Img/productosExfoliantes/naturesse.webp",
    title: "Naturesse",
    price: 39000,
    stock: 30,
    description: "Exfoliante natural que hidrata y purifica.",
  },
  {
    id: 11,
    img: "Img/productosExfoliantes/sephora.jpg",
    title: "Sephora",
    price: 65000,
    stock: 20,
    description: "Exfoliante premium para un acabado suave.",
  },
  {
    id: 12,
    img: "Img/productosExfoliantes/watermelon.webp",
    title: "Watermelon",
    price: 43000,
    stock: 25,
    description: "Refrescante exfoliante de sandía para la piel.",
  },
  {
    id: 13,
    img: "Img/productosLabios/colageno labios.png",
    title: "Colágeno Labios",
    price: 24000,
    stock: 50,
    description: "Bálsamo labial con colágeno para mayor hidratación.",
  },
  {
    id: 14,
    img: "Img/productosLabios/colageno.jpg",
    title: "Colágeno",
    price: 26000,
    stock: 40,
    description: "Fórmula para labios más voluminosos y suaves.",
  },
  {
    id: 15,
    img: "Img/productosLabios/exfoliante.jpeg",
    title: "Exfoliante Labios",
    price: 23000,
    stock: 35,
    description: "Suave exfoliación para unos labios sedosos.",
  },
  {
    id: 16,
    img: "Img/productosLabios/gloss.jpg",
    title: "Gloss",
    price: 22000,
    stock: 60,
    description: "Brillo labial que hidrata y da volumen.",
  },
  {
    id: 17,
    img: "Img/productosLabios/hidratante.jpg",
    title: "Hidratante Labios",
    price: 27000,
    stock: 30,
    description: "Hidratación intensa para labios secos.",
  },
  {
    id: 18,
    img: "Img/productosLabios/serum.webp",
    title: "Serum Labios",
    price: 35000,
    stock: 20,
    description: "Serum nutritivo para labios más saludables.",
  },
  {
    id: 19,
    img: "Img/productosLabios/voluminizante.webp",
    title: "Voluminizante Labios",
    price: 40000,
    stock: 25,
    description: "Aumenta el volumen y define los labios.",
  },
  {
    id: 20,
    img: "Img/productosMascarillas/class gold.jpeg",
    title: "Class Gold",
    price: 45000,
    stock: 30,
    description: "Mascarilla de lujo que ilumina la piel.",
  },
  {
    id: 21,
    img: "Img/productosMascarillas/gel2.jpg",
    title: "Gel 2",
    price: 30000,
    stock: 40,
    description: "Gel facial revitalizante y refrescante.",
  },
  {
    id: 22,
    img: "Img/productosMascarillas/kit body care.png",
    title: "Kit Body Care",
    price: 80000,
    stock: 15,
    description: "Kit completo para el cuidado del cuerpo.",
  },
  {
    id: 23,
    img: "Img/productosMascarillas/kit eva avo.webp",
    title: "Kit Eva Avo",
    price: 70000,
    stock: 20,
    description: "Mascarillas nutritivas con extracto de aguacate.",
  },
  {
    id: 24,
    img: "Img/productosMascarillas/weleda 2.jpg",
    title: "Weleda 2",
    price: 56000,
    stock: 25,
    description: "Mascarilla natural para una piel radiante.",
  },
  {
    id: 25,
    img: "Img/productosMascarillas/weleda.jpg",
    title: "Weleda",
    price: 58000,
    stock: 20,
    description: "Cuidado facial con ingredientes orgánicos.",
  },
  {
    id: 26,
    img: "Img/productosOjos/colageno trendy.jpg",
    title: "Colágeno Trendy",
    price: 30000,
    stock: 50,
    description: "Tratamiento de colágeno para la zona de los ojos.",
  },
  {
    id: 27,
    img: "Img/productosOjos/contorno ojos 2.webp",
    title: "Contorno Ojos 2",
    price: 35000,
    stock: 40,
    description: "Reduce las ojeras y la hinchazón en el contorno.",
  },
  {
    id: 28,
    img: "Img/productosOjos/desmaquillante.jpg",
    title: "Desmaquillante",
    price: 28000,
    stock: 30,
    description: "Elimina el maquillaje suavemente.",
  },
  {
    id: 29,
    img: "Img/productosOjos/gel pestañas 2.webp",
    title: "Gel Pestañas 2",
    price: 45000,
    stock: 20,
    description: "Fortalece y define las pestañas.",
  },
  {
    id: 30,
    img: "Img/productosOjos/kit pestañas.webp",
    title: "Kit Pestañas",
    price: 60000,
    stock: 15,
    description: "Todo lo necesario para unas pestañas perfectas.",
  },
  {
    id: 31,
    img: "Img/productosOjos/voluminizador cejas.webp",
    title: "Voluminizador Cejas",
    price: 32000,
    stock: 25,
    description: "Define y da volumen a tus cejas.",
  },
  {
    id: 32,
    img: "Img/productosRostro/agua micelar.jpg",
    title: "Agua Micelar",
    price: 29000,
    stock: 50,
    description: "Limpieza profunda y refrescante.",
  },
  {
    id: 33,
    img: "Img/productosRostro/crema hidratante.jpg",
    title: "Crema Hidratante",
    price: 41000,
    stock: 40,
    description: "Hidratación prolongada para todo tipo de piel.",
  },
  {
    id: 34,
    img: "Img/productosRostro/jabon barra.webp",
    title: "Jabón Barra",
    price: 22000,
    stock: 35,
    description: "Jabón suave que limpia sin resecar.",
  },
  {
    id: 35,
    img: "Img/productosRostro/kit ana maria.webp",
    title: "Kit Ana María",
    price: 75000,
    stock: 20,
    description: "Kit completo para el cuidado facial.",
  },
  {
    id: 36,
    img: "Img/productosRostro/mascarilla.webp",
    title: "Mascarilla",
    price: 34000,
    stock: 30,
    description: "Mascarilla hidratante que rejuvenece la piel.",
  },
  {
    id: 37,
    img: "Img/productosRostro/serum antimanchas.jpg",
    title: "Serum Antimanchas",
    price: 36000,
    stock: 25,
    description: "Tratamiento específico para manchas en la piel.",
  },
];
